name: fittask
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # или последнюю версию пакета
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15

environment:
  sdk: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
